application: dungeonshopper
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  login: admin

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  login: admin

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
  login: admin

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
  login: admin

- url: /images
  static_dir: images
  login: admin

- url: /
  static_files: static/index.html
  upload: static/index\.html
  login: admin

- url: .*
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
